// Generated by scripts\New-VaMShaders.py -- do not edit.
//
// The families this project reconstructs from the shipped shader bytecode. A material the
// game loads out of a bundle keeps the bundle's own copy of its shader even when this
// project defines one of the same name, and VamShaderProvider.UseProjectShader moves it
// across -- but only for a name in here. Shader.Find answers with the AssetRipper
// placeholders in Assets/Shader just as happily as with a reconstruction, so the list is
// what keeps a material that at least shades from being moved onto a stub that does not.

using System;
using System.Collections.Generic;

namespace MeshVR
{
	public static class VamProjectShaders
	{
		private static readonly string[] all =
		{
			"Custom/DebugNormalsComputeBuff",
			"Custom/Hair/Main",
			"Custom/Hair/MainAlternate",
			"Custom/Hair/MainAlternateComputeBuff",
			"Custom/Hair/MainComputeBuff",
			"Custom/Hair/MainSeparateAlphaLayer1",
			"Custom/Hair/MainSeparateAlphaLayer1ComputeBuff",
			"Custom/Hair/MainSeparateAlphaLayer2",
			"Custom/Hair/MainSeparateAlphaLayer2ComputeBuff",
			"Custom/Hair/MainSeparateAlphaLayer3",
			"Custom/Hair/MainSeparateAlphaLayer3ComputeBuff",
			"Custom/Hair/MainSeparateAlphaLayerFinal",
			"Custom/Hair/MainSeparateAlphaLayerFinalComputeBuff",
			"Custom/Hair/MainSeparateAlphaLayerScalp",
			"Custom/Hair/MainSeparateAlphaLayerScalpComputeBuff",
			"Custom/Hair/MainSeparateAlphaMimicAlpha",
			"Custom/Hair/MainSeparateAlphaMimicAlphaComputeBuff",
			"Custom/Hair/MainThicken",
			"Custom/Hair/MainThickenComputeBuff",
			"Custom/Hair/MainThickenSeparateAlpha",
			"Custom/Hair/MainThickenSeparateAlphaComputeBuff",
			"Custom/Hair/MainTransparentSeparateAlpha",
			"Custom/Hair/MainTransparentSeparateAlphaComputeBuff",
			"Custom/Hair/Scalp",
			"Custom/Hair/ScalpComputeBuff",
			"Custom/Hair/ScalpSeparateAlpha",
			"Custom/Hair/ScalpSeparateAlphaComputeBuff",
			"Custom/Hair/SimpleCutout",
			"Custom/Hair/SimpleCutoutComputeBuff",
			"Custom/Hair/SimpleCutoutSeparateAlpha",
			"Custom/Hair/SimpleCutoutSeparateAlphaComputeBuff",
			"Custom/Subsurface/AlphaMask",
			"Custom/Subsurface/AlphaMaskComputeBuff",
			"Custom/Subsurface/Cull",
			"Custom/Subsurface/CullComputeBuff",
			"Custom/Subsurface/Cutout",
			"Custom/Subsurface/CutoutComputeBuff",
			"Custom/Subsurface/CutoutNoCull",
			"Custom/Subsurface/CutoutNoCullComputeBuff",
			"Custom/Subsurface/CutoutSeparateAlpha",
			"Custom/Subsurface/CutoutSeparateAlphaComputeBuff",
			"Custom/Subsurface/CutoutSeparateAlphaNoCull",
			"Custom/Subsurface/CutoutSeparateAlphaNoCullComputeBuff",
			"Custom/Subsurface/GlossCull",
			"Custom/Subsurface/GlossCullComputeBuff",
			"Custom/Subsurface/GlossCutoutCull",
			"Custom/Subsurface/GlossCutoutCullComputeBuff",
			"Custom/Subsurface/GlossCutoutSeparateAlphaCull",
			"Custom/Subsurface/GlossCutoutSeparateAlphaCullComputeBuff",
			"Custom/Subsurface/GlossNMCull",
			"Custom/Subsurface/GlossNMCullComputeBuff",
			"Custom/Subsurface/GlossNMCutoutSeparateAlphaCull",
			"Custom/Subsurface/GlossNMCutoutSeparateAlphaCullComputeBuff",
			"Custom/Subsurface/GlossNMDetailCull",
			"Custom/Subsurface/GlossNMDetailCullComputeBuff",
			"Custom/Subsurface/GlossNMDetailTessMappedComputeBuff",
			"Custom/Subsurface/GlossNMNoCull",
			"Custom/Subsurface/GlossNMNoCullComputeBuff",
			"Custom/Subsurface/GlossNMTessMappedFixedComputeBuff",
			"Custom/Subsurface/GlossNoCull",
			"Custom/Subsurface/GlossNoCullComputeBuff",
			"Custom/Subsurface/GlossTessMappedFixedComputeBuff",
			"Custom/Subsurface/NoCull",
			"Custom/Subsurface/NoCullComputeBuff",
			"Custom/Subsurface/SSS",
			"Custom/Subsurface/SSSComputeBuff",
			"Custom/Subsurface/SSSTessMappedFixedComputeBuff",
			"Custom/Subsurface/TessMappedFixedComputeBuff",
			"Custom/Subsurface/Transparent",
			"Custom/Subsurface/TransparentComputeBuff",
			"Custom/Subsurface/TransparentCutoutSeparateAlpha",
			"Custom/Subsurface/TransparentCutoutSeparateAlphaComputeBuff",
			"Custom/Subsurface/TransparentGloss",
			"Custom/Subsurface/TransparentGlossComputeBuff",
			"Custom/Subsurface/TransparentGlossNMDetailNoCullSeparateAlpha",
			"Custom/Subsurface/TransparentGlossNMDetailNoCullSeparateAlphaComputeBuff",
			"Custom/Subsurface/TransparentGlossNMNoCullSeparateAlpha",
			"Custom/Subsurface/TransparentGlossNMNoCullSeparateAlphaComputeBuff",
			"Custom/Subsurface/TransparentGlossNMSeparateAlpha",
			"Custom/Subsurface/TransparentGlossNMSeparateAlphaComputeBuff",
			"Custom/Subsurface/TransparentGlossNoCull",
			"Custom/Subsurface/TransparentGlossNoCullComputeBuff",
			"Custom/Subsurface/TransparentGlossNoCullSeparateAlpha",
			"Custom/Subsurface/TransparentGlossNoCullSeparateAlphaComputeBuff",
			"Custom/Subsurface/TransparentGlossSeparateAlpha",
			"Custom/Subsurface/TransparentGlossSeparateAlphaComputeBuff",
			"Custom/Subsurface/TransparentSeparateAlpha",
			"Custom/Subsurface/TransparentSeparateAlphaComputeBuff",
		};

		private static readonly HashSet<string> lookup =
			new HashSet<string>(all, StringComparer.Ordinal);

		public static bool Defines(string shaderName)
		{
			return shaderName != null && lookup.Contains(shaderName);
		}
	}
}
