#Requires -Version 5.1
<#
.SYNOPSIS
    Generates src/UnityReferences.props from the DLLs shipped in Virt-a-Mate_Data\Managed.

.DESCRIPTION
    BCL/Mono assemblies that ship with the game must NOT be referenced, because the
    rebuild targets the real .NET Framework 4.7.2 reference assemblies. Only the
    Unity engine modules and third-party libraries are emitted as references.
#>
param(
    [string]$ManagedDir = (Join-Path $PSScriptRoot '..\..\VaM_Data\Managed'),
    [string]$OutFile    = (Join-Path $PSScriptRoot '..\src\UnityReferences.props')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $ManagedDir)) {
    throw "Managed directory not found: $ManagedDir"
}

$ManagedDir = (Resolve-Path -LiteralPath $ManagedDir).Path
$OutFile    = [System.IO.Path]::GetFullPath($OutFile)

# Assemblies replaced by the .NET Framework 4.7.2 reference assemblies shipped with the SDK.
$excludedNames = @(
    'mscorlib', 'netstandard', 'Accessibility'
    'System', 'System.Core', 'System.Configuration', 'System.Data', 'System.Drawing'
    'System.EnterpriseServices', 'System.Runtime.Serialization', 'System.Security'
    'System.Transactions', 'System.Windows.Forms', 'System.Xml'
    'Mono.Data.Tds', 'Mono.Posix', 'Mono.Security', 'Mono.WebBrowser'
    # The artifacts we are rebuilding: referencing them would defeat the purpose.
    'Assembly-CSharp', 'Assembly-UnityScript'
)

# Boo.Lang is the runtime UnityScript-generated code compiles against, so it stays.

$refs = Get-ChildItem -LiteralPath $ManagedDir -Filter *.dll -File |
    Where-Object { $excludedNames -notcontains $_.BaseName } |
    Sort-Object Name

if ($refs.Count -eq 0) { throw "No referenceable assemblies found in $ManagedDir" }

# [System.IO.Path]::GetRelativePath is .NET Core-only, so compute the relative path by hand.
$outDirUri = [System.Uri]::new(((Split-Path -Parent $OutFile).TrimEnd('\') + '\'))
$managedUri = [System.Uri]::new(($ManagedDir.TrimEnd('\') + '\'))
$relativeManaged = [System.Uri]::UnescapeDataString(
    $outDirUri.MakeRelativeUri($managedUri).ToString()) -replace '/', '\'
$relativeManaged = $relativeManaged.TrimEnd('\')

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('<Project>')
[void]$sb.AppendLine('  <!-- GENERATED by scripts/Update-UnityReferences.ps1 - do not edit by hand. -->')
[void]$sb.AppendLine('  <PropertyGroup>')
# Emit the path relative to this file where possible: that is what keeps the generated file
# portable. It has to be anchored on MSBuildThisFileDirectory, because a bare relative HintPath
# resolves against each project's own directory, and one of them sits two levels deeper.
# A relative path cannot exist across volumes, and there the absolute one is used.
$defaultManaged = if ($relativeManaged -and -not $relativeManaged.Contains(':')) {
    "`$(MSBuildThisFileDirectory)$relativeManaged"
} else {
    $ManagedDir
}
[void]$sb.AppendLine('    <!-- Point this at another installation with the VamManagedDir environment variable (or /p:VamManagedDir=). -->')
[void]$sb.AppendLine("    <VamManagedDir>$defaultManaged</VamManagedDir>")
[void]$sb.AppendLine('  </PropertyGroup>')
[void]$sb.AppendLine('  <ItemGroup>')
foreach ($ref in $refs) {
    [void]$sb.AppendLine("    <Reference Include=""$($ref.BaseName)"">")
    [void]$sb.AppendLine("      <HintPath>`$(VamManagedDir)\$($ref.Name)</HintPath>")
    [void]$sb.AppendLine('      <Private>false</Private>')
    [void]$sb.AppendLine('    </Reference>')
}
[void]$sb.AppendLine('  </ItemGroup>')
[void]$sb.AppendLine('</Project>')

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), $utf8NoBom)

Write-Host "Wrote $($refs.Count) references to $OutFile"
$refs | Select-Object -ExpandProperty Name
